/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Seguridad.Usuario;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.ImageIcon;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author donald
 */
public class menu extends javax.swing.JFrame {
    private static Usuario user;//variable global del usuario 

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.user=user;
        this.setLocationRelativeTo(null);
    }
    public menu(Usuario user){
        initComponents();
        this.user=user;//Se asigna el usuaario que hizo login
        this.setLocationRelativeTo(null);
    }
    public void seguridad(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUsuarios = new javax.swing.JButton();
        jButtonAnadirUsuario = new javax.swing.JButton();
        jButtonVenta = new javax.swing.JButton();
        jButtonInventario = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Usuario1.png"))); // NOI18N
        jButtonUsuarios.setBorderPainted(false);
        jButtonUsuarios.setContentAreaFilled(false);
        jButtonUsuarios.setPreferredSize(new java.awt.Dimension(98, 74));
        jButtonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 80, 50));

        jButtonAnadirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Agregar_Usuario.png"))); // NOI18N
        jButtonAnadirUsuario.setBorderPainted(false);
        jButtonAnadirUsuario.setContentAreaFilled(false);
        jButtonAnadirUsuario.setPreferredSize(new java.awt.Dimension(98, 74));
        jButtonAnadirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnadirUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 80, 60));

        jButtonVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Venta.png"))); // NOI18N
        jButtonVenta.setBorderPainted(false);
        jButtonVenta.setContentAreaFilled(false);
        jButtonVenta.setPreferredSize(new java.awt.Dimension(98, 74));
        jButtonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 70, 70));

        jButtonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Inventario.png"))); // NOI18N
        jButtonInventario.setBorderPainted(false);
        jButtonInventario.setContentAreaFilled(false);
        jButtonInventario.setPreferredSize(new java.awt.Dimension(98, 74));
        jButtonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 80, 70));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/menu.png"))); // NOI18N
        jButtonMenu.setBorderPainted(false);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setPreferredSize(new java.awt.Dimension(98, 74));
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 70, 70));

        jButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ClientesNegro.png"))); // NOI18N
        jButtonCliente.setBorderPainted(false);
        jButtonCliente.setContentAreaFilled(false);
        jButtonCliente.setPreferredSize(new java.awt.Dimension(98, 74));
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 70, 60));

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInventarioActionPerformed
        Inventario in = new Inventario();
        this.setVisible(false);
        in.setVisible(true);
    }//GEN-LAST:event_jButtonInventarioActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        /*Menu2 menu = new Menu2();
        this.setVisible(false);
        menu.setVisible(true);*/
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        Cliente cliente = new Cliente();
        this.setVisible(false);
        cliente.setVisible(true);
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonAnadirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirUsuarioActionPerformed
        AnadirUsuario user = new AnadirUsuario();
        this.setVisible(false);
        user.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirUsuarioActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        Usuarios user = new Usuarios();
        this.setVisible(false);
        user.setVisible(true);
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentaActionPerformed
        Venta venta = new Venta();
        this.setVisible(false);
        venta.setVisible(true);
    }//GEN-LAST:event_jButtonVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirUsuario;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonInventario;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JButton jButtonVenta;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables

}
